---
dataset_path: 'C:\Users\Sichao\Desktop\Jun25\v5\dataset_pickle'
model_save_path: '.\modelGen\'
pred_pickle_path:  '.\pickle_data\'
model_name: distillation_model_v3_1

draw_label_size:
    default:
        5

train_parameters:
    loss:
        - binary_crossentropy
        - mean_squared_error
        - mean_squared_error

    loss_weights:
        - 1
        - 1
        - 2
        - 4

    metrics:
        - binary_crossentropy
        - mae
        - mae

    optimizer_used: SGD

    optimizer_SGD:
        learning_rate: 0.01
        momentum: 0.95
        nesterov: True

    optimizer_Adam:
        learning_rate: 0.01
        beta_1: 0.9
        beta_2: 0.999
        epsilon: 1e-07
        amsgrad: False

    epoch: 75
    batch_size: 32
    shuffle: True

