---
dataset_path: 'C:\Users\Sichao\Desktop\Jun25\v5\dataset_pickle'
output_save_path: '.\result\'

draw_label_size:
    default:
        5

event_key_list:
    # 1: save and next,  2:Next img,   3:previous img,  4:Insert Empty Label,  5:Delete Label
    SNN: space
    NI:
    PI:
    IEL: Control_L
    DL: BackSpace

default_empty_label:
    - 9999  # x
    - 9999  # y

#  0: keypoint  1: boundingbox
default_draw_method: 1

resize_img: False
